Controllers/ProviderController.cs
using FinalProject.Models;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Controllers
{
    public class ProviderController : Controller
    {
        public IActionResult List()
        {
            IEnumerable<TProvider> datas = null;
            FinalProjectContext db = new FinalProjectContext();
            datas = from t in db.TProviders
                    select t;
            return View(datas);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(TProvider p)
        {
            FinalProjectContext db = new FinalProjectContext();
            db.TProviders.Add(p);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        public ActionResult Delete(int? id)
        {
            if (id != null)
            {
                FinalProjectContext db = new FinalProjectContext();
                TProvider delProvider = db.TProviders.FirstOrDefault(t => t.FId == id);
                if (delProvider != null)
                {
                    db.TProviders.Remove(delProvider);
                    db.SaveChangesAsync();
                }
            }
            return RedirectToAction("List");
        }

        [HttpPost]
        public ActionResult Edit(TProvider p)
        {
            FinalProjectContext db = new FinalProjectContext();
            TProvider x = db.TProviders.FirstOrDefault(t => t.FId == p.FId);
            if (x != null)
            {
                x.FCompanyName = p.FCompanyName;
                x.FPassword = p.FPassword;
                x.FTaxId = p.FTaxId;
                x.FFax = p.FFax;
                x.FOwnerName = p.FOwnerName;
                x.FOwnerTel = p.FOwnerTel;
                x.FOwnerMobile = p.FOwnerMobile;
                x.FOwnerEmail = p.FOwnerEmail;
                x.FOwnerName = p.FOwnerName;
                x.FContactTel = p.FContactTel;
                x.FContactMobile = p.FContactMobile;
                x.FContactEmail = p.FContactEmail;
                x.FAddress = p.FAddress;
                x.FBankName = p.FBankName;
                x.FBankDivisionName = p.FBankDivisionName;
                x.FBankAccountNumber = p.FBankAccountNumber;
                x.FBankAccountName = p.FBankAccountName;
                x.FBlackList = p.FBlackList;
                x.FRemark = p.FRemark;
                x.FCreationDate = p.FCreationDate;
                x.FLastUpdateDate = p.FLastUpdateDate;
                db.SaveChangesAsync();
            }
            return RedirectToAction("List");
        }

        public ActionResult Edit(int? id)
        {
            if (id != null)
            {
                FinalProjectContext db = new FinalProjectContext();
                TProvider x = db.TProviders.FirstOrDefault(t => t.FId == id);
                if (x != null)
                    return View(x);
            }
            return RedirectToAction("List");
        }
    }
}

Views/Provider/Create.cshtml
@model FinalProject.Models.TProvider

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TProvider</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="FId" class="control-label"></label>
                <input asp-for="FId" class="form-control" />
                <span asp-validation-for="FId" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="FCompanyName" class="control-label"></label>
                <input asp-for="FCompanyName" class="form-control" />
                <span asp-validation-for="FCompanyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FPassword" class="control-label"></label>
                <input asp-for="FPassword" class="form-control" />
                <span asp-validation-for="FPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FTaxId" class="control-label"></label>
                <input asp-for="FTaxId" class="form-control" />
                <span asp-validation-for="FTaxId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FFax" class="control-label"></label>
                <input asp-for="FFax" class="form-control" />
                <span asp-validation-for="FFax" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FOwnerName" class="control-label"></label>
                <input asp-for="FOwnerName" class="form-control" />
                <span asp-validation-for="FOwnerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FOwnerTel" class="control-label"></label>
                <input asp-for="FOwnerTel" class="form-control" />
                <span asp-validation-for="FOwnerTel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FOwnerMobile" class="control-label"></label>
                <input asp-for="FOwnerMobile" class="form-control" />
                <span asp-validation-for="FOwnerMobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FOwnerEmail" class="control-label"></label>
                <input asp-for="FOwnerEmail" class="form-control" />
                <span asp-validation-for="FOwnerEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FContactName" class="control-label"></label>
                <input asp-for="FContactName" class="form-control" />
                <span asp-validation-for="FContactName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FContactTel" class="control-label"></label>
                <input asp-for="FContactTel" class="form-control" />
                <span asp-validation-for="FContactTel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FContactMobile" class="control-label"></label>
                <input asp-for="FContactMobile" class="form-control" />
                <span asp-validation-for="FContactMobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FContactEmail" class="control-label"></label>
                <input asp-for="FContactEmail" class="form-control" />
                <span asp-validation-for="FContactEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FAddress" class="control-label"></label>
                <input asp-for="FAddress" class="form-control" />
                <span asp-validation-for="FAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FBankName" class="control-label"></label>
                <input asp-for="FBankName" class="form-control" />
                <span asp-validation-for="FBankName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FBankDivisionName" class="control-label"></label>
                <input asp-for="FBankDivisionName" class="form-control" />
                <span asp-validation-for="FBankDivisionName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FBankAccountNumber" class="control-label"></label>
                <input asp-for="FBankAccountNumber" class="form-control" />
                <span asp-validation-for="FBankAccountNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FBankAccountName" class="control-label"></label>
                <input asp-for="FBankAccountName" class="form-control" />
                <span asp-validation-for="FBankAccountName" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="FBlackList" /> @Html.DisplayNameFor(model => model.FBlackList)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="FRemark" class="control-label"></label>
                <input asp-for="FRemark" class="form-control" />
                <span asp-validation-for="FRemark" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FCreationDate" class="control-label"></label>
                <input asp-for="FCreationDate" class="form-control" />
                <span asp-validation-for="FCreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FLastUpdateDate" class="control-label"></label>
                <input asp-for="FLastUpdateDate" class="form-control" />
                <span asp-validation-for="FLastUpdateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Provider/Edit.cshtml
@model FinalProject.Models.TProvider

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TProvider</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="display:none">
                <label asp-for="FId" class="control-label"></label>
                <input asp-for="FId" class="form-control" />
                <span asp-validation-for="FId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FCompanyName" class="control-label"></label>
                <input asp-for="FCompanyName" class="form-control" />
                <span asp-validation-for="FCompanyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FPassword" class="control-label"></label>
                <input asp-for="FPassword" class="form-control" />
                <span asp-validation-for="FPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FTaxId" class="control-label"></label>
                <input asp-for="FTaxId" class="form-control" />
                <span asp-validation-for="FTaxId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FFax" class="control-label"></label>
                <input asp-for="FFax" class="form-control" />
                <span asp-validation-for="FFax" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FOwnerName" class="control-label"></label>
                <input asp-for="FOwnerName" class="form-control" />
                <span asp-validation-for="FOwnerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FOwnerTel" class="control-label"></label>
                <input asp-for="FOwnerTel" class="form-control" />
                <span asp-validation-for="FOwnerTel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FOwnerMobile" class="control-label"></label>
                <input asp-for="FOwnerMobile" class="form-control" />
                <span asp-validation-for="FOwnerMobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FOwnerEmail" class="control-label"></label>
                <input asp-for="FOwnerEmail" class="form-control" />
                <span asp-validation-for="FOwnerEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FContactName" class="control-label"></label>
                <input asp-for="FContactName" class="form-control" />
                <span asp-validation-for="FContactName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FContactTel" class="control-label"></label>
                <input asp-for="FContactTel" class="form-control" />
                <span asp-validation-for="FContactTel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FContactMobile" class="control-label"></label>
                <input asp-for="FContactMobile" class="form-control" />
                <span asp-validation-for="FContactMobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FContactEmail" class="control-label"></label>
                <input asp-for="FContactEmail" class="form-control" />
                <span asp-validation-for="FContactEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FAddress" class="control-label"></label>
                <input asp-for="FAddress" class="form-control" />
                <span asp-validation-for="FAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FBankName" class="control-label"></label>
                <input asp-for="FBankName" class="form-control" />
                <span asp-validation-for="FBankName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FBankDivisionName" class="control-label"></label>
                <input asp-for="FBankDivisionName" class="form-control" />
                <span asp-validation-for="FBankDivisionName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FBankAccountNumber" class="control-label"></label>
                <input asp-for="FBankAccountNumber" class="form-control" />
                <span asp-validation-for="FBankAccountNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FBankAccountName" class="control-label"></label>
                <input asp-for="FBankAccountName" class="form-control" />
                <span asp-validation-for="FBankAccountName" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="FBlackList" /> @Html.DisplayNameFor(model => model.FBlackList)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="FRemark" class="control-label"></label>
                <input asp-for="FRemark" class="form-control" />
                <span asp-validation-for="FRemark" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FCreationDate" class="control-label"></label>
                <input asp-for="FCreationDate" class="form-control" />
                <span asp-validation-for="FCreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FLastUpdateDate" class="control-label"></label>
                <input asp-for="FLastUpdateDate" class="form-control" />
                <span asp-validation-for="FLastUpdateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Provider/List.cshtml
@model IEnumerable<FinalProject.Models.TProvider>

@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

<p>
    <a asp-action="Create">新增資料</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                序
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FCompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FPassword)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FTaxId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FFax)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FOwnerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FOwnerTel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FOwnerMobile)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FOwnerEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FContactName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FContactTel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FContactMobile)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FContactEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FBankName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FBankDivisionName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FBankAccountNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FBankAccountName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FBlackList)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FRemark)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FCreationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FLastUpdateDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            int count = 0;
            foreach (var item in Model)
            {
                count++;
                <tr>
                    <td>
                        @count
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FCompanyName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FPassword)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FTaxId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FFax)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FOwnerName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FOwnerTel)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FOwnerMobile)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FOwnerEmail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FContactName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FContactTel)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FContactMobile)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FContactEmail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FAddress)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FBankName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FBankDivisionName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FBankAccountNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FBankAccountName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FBlackList)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FRemark)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FCreationDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FLastUpdateDate)
                    </td>
                    <td>
                        @Html.ActionLink("修改", "Edit", new { id = item.FId }, new { @class = "btn btn-success" })
                        @Html.ActionLink("刪除", "Delete", "Provider", new { id = item.FId }, new { onclick = "return confirm('確定要刪除?\\n\\r刪除後將無法復原!')", @class = "btn btn-danger" })
                    </td>
                </tr>
            }
        }
    </tbody>
</table>